"""empty message

Revision ID: 423cc283d259
Revises: 03999b411ecc
Create Date: 2021-07-04 15:38:55.882972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423cc283d259'
down_revision = '03999b411ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###
